apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-events-controller-manager
  namespace: argo-events
  labels:
    app.kubernetes.io/name: argo-events-controller-manager
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: argo-events
    app.kubernetes.io/part-of: argo-events
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-events-controller-manager
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/instance: argo-events
      app.kubernetes.io/part-of: argo-events
  namespaceSelector:
    matchNames:
      - argo-events
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
